services:
 db:
   image: postgres:17.2-bookworm
   environment:
     POSTGRES_DB: ${DATABASE_NAME}
     POSTGRES_USER: ${DATABASE_USERNAME}
     POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
   ports:
     - "5432:5432"
   volumes:
     - postgres_data:/var/lib/postgresql/data
   env_file:
     - .env

 web:
   build: .
   container_name: titans-manager
   ports:
     - "8000:8000"
   depends_on:
     - db
   volumes:
     - static_volume:/app/staticfiles
     - media_volume:/app/media
   environment:
     DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
     DEBUG: ${DEBUG}
     DJANGO_LOGLEVEL: ${DJANGO_LOGLEVEL}
     DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
     DATABASE_ENGINE: ${DATABASE_ENGINE}
     DATABASE_NAME: ${DATABASE_NAME}
     DATABASE_USERNAME: ${DATABASE_USERNAME}
     DATABASE_PASSWORD: ${DATABASE_PASSWORD}
     DATABASE_PORT: ${DATABASE_PORT}
     STATIC_ROOT: /app/staticfiles
     MEDIA_ROOT: /app/media
   env_file:
     - .env
volumes:
   postgres_data:
   static_volume:
   media_volume:
