# Generated by Django 5.1.5 on 2025-01-31 02:13

import core.custom_storage
import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='receipt',
            field=models.FileField(blank=True, null=True, storage=core.custom_storage.AzureReceiptStorage(), upload_to=core.models.Expense.receipt_upload_path),
        ),
    ]
