# Generated by Django 5.1.5 on 2025-02-06 00:06

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_expense_receipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tax_year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2000)])),
                ('quarter', models.PositiveIntegerField(blank=True, choices=[(1, 'Q1'), (2, 'Q2'), (3, 'Q3'), (4, 'Q4')], null=True)),
                ('total_income', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('taxable_income', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('federal_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('provincial_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('total_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('effective_tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('calculation_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tax Calculation',
                'verbose_name_plural': 'Tax Calculations',
                'ordering': ['-tax_year', '-quarter'],
                'indexes': [models.Index(fields=['tax_year'], name='core_taxcal_tax_yea_b44ad4_idx'), models.Index(fields=['calculation_date'], name='core_taxcal_calcula_30d804_idx')],
                'unique_together': {('tax_year', 'quarter')},
            },
        ),
    ]
