# Generated by Django 5.1.5 on 2025-02-06 00:27

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_project_expenses_taxcalculation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxcalculation',
            name='effective_tax_rate',
        ),
        migrations.AddField(
            model_name='taxcalculation',
            name='balance_due',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Remaining balance to be paid', max_digits=18),
        ),
        migrations.AddField(
            model_name='taxcalculation',
            name='installments_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total tax installments already paid', max_digits=18),
        ),
        migrations.AddField(
            model_name='taxcalculation',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, help_text='Date when this calculation was last updated'),
        ),
        migrations.AddField(
            model_name='taxcalculation',
            name='payment_due_date',
            field=models.DateField(blank=True, help_text='Due date for tax payment', null=True),
        ),
        migrations.AddField(
            model_name='taxcalculation',
            name='status',
            field=models.CharField(choices=[('estimated', 'Estimated'), ('filed', 'Filed'), ('paid', 'Paid'), ('pending', 'Pending')], default='estimated', help_text='Current status of this tax calculation', max_length=20),
        ),
        migrations.AlterField(
            model_name='taxcalculation',
            name='calculation_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Date when this calculation was performed'),
        ),
        migrations.AlterField(
            model_name='taxcalculation',
            name='federal_tax',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Federal portion of tax', max_digits=18),
        ),
        migrations.AlterField(
            model_name='taxcalculation',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes or comments about this tax calculation', null=True),
        ),
        migrations.AlterField(
            model_name='taxcalculation',
            name='provincial_tax',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Provincial portion of tax', max_digits=18),
        ),
        migrations.AlterField(
            model_name='taxcalculation',
            name='quarter',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Q1 (Jan-Mar)'), (2, 'Q2 (Apr-Jun)'), (3, 'Q3 (Jul-Sep)'), (4, 'Q4 (Oct-Dec)')], help_text='Quarter for this calculation (if applicable)', null=True),
        ),
        migrations.AlterField(
            model_name='taxcalculation',
            name='tax_year',
            field=models.PositiveIntegerField(help_text='Tax year for this calculation', validators=[django.core.validators.MinValueValidator(2000)]),
        ),
        migrations.AlterField(
            model_name='taxcalculation',
            name='taxable_income',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Income subject to tax after deductions', max_digits=18),
        ),
        migrations.AlterField(
            model_name='taxcalculation',
            name='total_expenses',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total deductible expenses', max_digits=18),
        ),
        migrations.AlterField(
            model_name='taxcalculation',
            name='total_income',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total income before deductions', max_digits=18),
        ),
        migrations.AlterField(
            model_name='taxcalculation',
            name='total_tax',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total tax payable (federal + provincial)', max_digits=18),
        ),
        migrations.AddIndex(
            model_name='taxcalculation',
            index=models.Index(fields=['status'], name='core_taxcal_status_b1faf7_idx'),
        ),
    ]
