# Generated by Django 5.1.5 on 2025-01-29 03:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='expense',
            name='project',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='receipt_url',
        ),
        migrations.AddField(
            model_name='expense',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='due_date',
            field=models.DateField(blank=True, help_text='Due date for payment if applicable', null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expense',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='paid_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('paypal', 'PayPal'), ('other', 'Other')], default='debit_card', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Reference number, cheque number, or transaction ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='receipts/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='expense',
            name='recurring_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='recurring_frequency',
            field=models.CharField(choices=[('none', 'Not Recurring'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='expense',
            name='submitted_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_expenses', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
        ),
        migrations.AddField(
            model_name='expense',
            name='tax_status',
            field=models.CharField(choices=[('taxable', 'Taxable'), ('non_taxable', 'Non-Taxable')], default='taxable', max_length=20),
        ),
        migrations.AddField(
            model_name='expense',
            name='title',
            field=models.CharField(default='Sample Expense', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='vendor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='vendor_tax_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('rent', 'Rent/Lease'), ('utilities', 'Utilities'), ('software', 'Software/Tools'), ('hardware', 'Hardware/Equipment'), ('travel', 'Travel'), ('salaries', 'Salaries/Payroll'), ('marketing', 'Marketing'), ('office', 'Office Supplies'), ('insurance', 'Insurance'), ('taxes', 'Taxes'), ('maintenance', 'Maintenance'), ('professional', 'Professional Services'), ('training', 'Training/Education'), ('other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(help_text='Date of expense'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['date'], name='core_expens_date_d957f6_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['category'], name='core_expens_categor_358de0_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['status'], name='core_expens_status_32e345_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['is_recurring'], name='core_expens_is_recu_9e3925_idx'),
        ),
    ]
