apiVersion: apps/v1
kind: Deployment
metadata:
  name: tms-app
  namespace: wackops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tms-app
  template:
    metadata:
      labels:
        app: tms-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nodepoolos
                operator: In
                values:
                - linux
      initContainers:
      - name: migrate
        image: wackopsprodacr.azurecr.io/tms:0.1.4
        command: ["python", "manage.py", "migrate"]
        env:
        - name: DJANGO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: tms-secret
              key: DJANGO_SECRET_KEY
        - name: DEBUG
          valueFrom:
            configMapKeyRef:
              name: tms-config
              key: DEBUG
        - name: DJANGO_LOGLEVEL
          valueFrom:
            configMapKeyRef:
              name: tms-config
              key: DJANGO_LOGLEVEL
        - name: DJANGO_ALLOWED_HOSTS
          valueFrom:
            configMapKeyRef:
              name: tms-config
              key: DJANGO_ALLOWED_HOSTS
        - name: AZURE_ACCOUNT_NAME
          valueFrom:
            secretKeyRef:
              name: azure-storage-secret
              key: AZURE_ACCOUNT_NAME
        - name: AZURE_ACCOUNT_KEY
          valueFrom:
            secretKeyRef:
              name: azure-storage-secret
              key: AZURE_ACCOUNT_KEY
        - name: DATABASE_ENGINE
          value: postgresql_psycopg2
        - name: DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: tms-secret
              key: DATABASE_NAME
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: tms-secret
              key: DATABASE_USERNAME
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tms-secret
              key: DATABASE_PASSWORD
        - name: DATABASE_HOST
          valueFrom:
            secretKeyRef:
              name: tms-secret
              key: DATABASE_HOST
        - name: DATABASE_PORT
          valueFrom:
            configMapKeyRef:
              name: tms-config
              key: DATABASE_PORT
      containers:
      - name: titans-manager
        image: wackopsprodacr.azurecr.io/tms:0.1.4
        ports:
        - containerPort: 8000
        env:
        - name: DJANGO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: tms-secret
              key: DJANGO_SECRET_KEY
        - name: DEBUG
          valueFrom:
            configMapKeyRef:
              name: tms-config
              key: DEBUG
        - name: DJANGO_LOGLEVEL
          valueFrom:
            configMapKeyRef:
              name: tms-config
              key: DJANGO_LOGLEVEL
        - name: DJANGO_ALLOWED_HOSTS
          valueFrom:
            configMapKeyRef:
              name: tms-config
              key: DJANGO_ALLOWED_HOSTS
        - name: DATABASE_ENGINE
          value: postgresql_psycopg2
        - name: DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: tms-secret
              key: DATABASE_NAME
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: tms-secret
              key: DATABASE_USERNAME
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tms-secret
              key: DATABASE_PASSWORD
        - name: DATABASE_HOST
          valueFrom:
            secretKeyRef:
              name: tms-secret
              key: DATABASE_HOST
        - name: DATABASE_PORT
          valueFrom:
            configMapKeyRef:
              name: tms-config
              key: DATABASE_PORT
        - name: AZURE_ACCOUNT_NAME
          valueFrom:
            secretKeyRef:
              name: azure-storage-secret
              key: AZURE_ACCOUNT_NAME
        - name: AZURE_ACCOUNT_KEY
          valueFrom:
            secretKeyRef:
              name: azure-storage-secret
              key: AZURE_ACCOUNT_KEY
        - name: CSRF_TRUSTED_ORIGINS
          valueFrom:
            configMapKeyRef:
              name: tms-config
              key: CSRF_TRUSTED_ORIGINS
        volumeMounts:
        - name: static-volume
          mountPath: /app/staticfiles
        - name: media-volume
          mountPath: /app/media
      volumes:
      - name: static-volume
        persistentVolumeClaim:
          claimName: static
      - name: media-volume
        persistentVolumeClaim:
          claimName: media