apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-pvc
  namespace: wackops
spec:
  storageClassName: azurefile-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-pvc
  namespace: wackops
spec:
  storageClassName: azurefile-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi