name: Run Pytest

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17.2
        env:
          POSTGRES_DB: tmsdb
          POSTGRES_USER: dbuser
          POSTGRES_PASSWORD: dbpassword
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U test_user -d test_db"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        

    - name: Run tests
      env:
        DATABASE_NAME: tmsdb
        DATABASE_USERNAME: dbuser
        DATABASE_PASSWORD: dbpassword
        DATABASE_HOST: localhost
        DATABASE_PORT: 5432
      run: |
        pytest
